import type { SnapConfig } from '@metamask/snaps-cli';
import { merge } from '@metamask/snaps-cli';
import { resolve } from 'path';
import { mkdirSync, copyFileSync, cpSync } from 'fs';
import * as webpack from 'webpack';
import stdLibBrowser from 'node-stdlib-browser';

/**
 * E2E-only Snap build/serve config. It mirrors `snap.config.ts` (keep the two in sync) for the
 * bundle itself and differs in exactly one respect: it builds and serves the Snap from a
 * throwaway directory OUTSIDE the repo so MetaMask receives a manifest whose `shasum` matches
 * the locally-built bundle — WITHOUT ever rewriting the committed `packages/snap/snap.manifest.json`.
 *
 * Why this is needed:
 *   - The committed manifest shasum is the published one; a locally-built bundle hashes
 *     differently (toolchain / dependency drift).
 *   - MetaMask Flask DOES enforce the manifest source-integrity check for `local:` Snaps.
 *     Installing a Snap whose served manifest shasum differs from the served bundle fails with
 *     "Invalid Snap manifest: manifest shasum does not match computed shasum", which aborts the
 *     dApp connect flow before the Snap is ever installed.
 *   - The Snaps CLI dev server always reads/serves the manifest from
 *     `<server.root>/snap.manifest.json` and (when `manifest.update` is on) regenerates it at
 *     `manifest.path`. Pointing `output.path`, `manifest.path` and `server.root` at a temp
 *     directory — seeded below with a copy of the manifest and icon — lets `manifest.update: true`
 *     produce a matching shasum there, leaving `packages/snap` byte-identical to what is published.
 *
 * This file is not part of the published package (`package.json#files`); it exists purely to
 * drive the E2E dev server. It cannot `import` from `snap.config.ts` because the Snaps CLI
 * config loader does not resolve nested `.ts` imports, hence the small amount of duplication.
 */

// Throwaway build/serve root. Kept UNDER `packages/snap/dist/` (gitignored, cleaned by `yarn
// clean`) for two reasons: it leaves no tracked footprint, and — crucially — it stays nested in
// `packages/snap` so the Snaps CLI manifest validators (which `createRequire` from the manifest's
// location, e.g. to read `@metamask/snaps-sdk/package.json`) resolve through `packages/snap/node_modules`.
const E2E_SERVE_ROOT = resolve(__dirname, 'dist', '.e2e-server');

// Seed the serve root with a writable copy of the manifest (its shasum is regenerated by
// `manifest.update`), the `package.json` that `checkManifest` cross-checks the manifest against,
// and the icon the manifest references. Runs at config-load time, before the Snaps CLI builds/serves.
mkdirSync(E2E_SERVE_ROOT, { recursive: true });
copyFileSync(
  resolve(__dirname, 'snap.manifest.json'),
  resolve(E2E_SERVE_ROOT, 'snap.manifest.json'),
);
copyFileSync(
  resolve(__dirname, 'package.json'),
  resolve(E2E_SERVE_ROOT, 'package.json'),
);
cpSync(resolve(__dirname, 'images'), resolve(E2E_SERVE_ROOT, 'images'), { recursive: true });

const config: SnapConfig = {
  bundler: 'webpack',
  customizeWebpackConfig: (config) => merge(config, {
    mode: 'production',
    resolve: {
      fallback: {
        crypto: stdLibBrowser.crypto,
        stream: stdLibBrowser.stream,
        buffer: require.resolve('buffer'),
        process: stdLibBrowser.process,
        path: stdLibBrowser.path,
        fs: false,
        util: stdLibBrowser.util,
        assert: stdLibBrowser.assert,
      },
    },
    plugins: [
      ...(config.plugins || []),
      new webpack.ProvidePlugin({
        Buffer: ['buffer', 'Buffer'],
      }),
      new webpack.DefinePlugin({
        'process.browser': true,
      }),
    ],
  }),
  input: resolve(__dirname, 'src/index.tsx'),
  // Build the bundle into the throwaway serve root (manifest references it as `dist/bundle.js`).
  output: {
    path: resolve(E2E_SERVE_ROOT, 'dist'),
  },
  server: {
    port: 8080,
    // Serve the seeded copy, never the committed `packages/snap`.
    root: E2E_SERVE_ROOT,
  },
  polyfills: true,
  environment: {
    NODE_ENV: 'production',
  },
  // Regenerate the shasum so the served manifest matches the served bundle. The write lands in
  // the throwaway serve root (see `manifest.path`), never in the committed manifest.
  manifest: {
    path: resolve(E2E_SERVE_ROOT, 'snap.manifest.json'),
    update: true,
  },
};

export default config;
